name: Terraform CI

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [main]   # optional, runs on push to main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.7

      - name: Terraform Format
        working-directory: Day-1-basic-code
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: Day-1-basic-code
        run: terraform init

      - name: Terraform Validate
        working-directory: Day-1-basic-code
        run: terraform validate

      - name: Terraform Plan
        working-directory: Day-1-basic-code
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: Day-1-basic-code
        run: terraform apply -auto-approve tfplan
